### ISSUE TITLE
无法上传中文文件名图片

### ISSUE THREAD

**Issue by raawaa** [xizhonghua/yssybbsuploader#2]
遇到中文文件名图片时就报错，上传的文件名为「白1.jpg」：

``` bash
Traceback (most recent call last):
  File "/home/raawaa/Code/yssybbsuploader/src/bbsupload.py", line 281, in <module>
    uploader.post()
  File "/home/raawaa/Code/yssybbsuploader/src/bbsupload.py", line 161, in post
    [self] * len(files), files))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by xizhonghua** [comment]
debug了一下，估计是bbs不支持uniccode编码的文件名...
我只能hack了，如果文件名含有non-ascii字符，一律先另存为纯英文文件名的版本... 
缺点是文件夹下会创建很多临时文件
凑合用用吧

**Comment by raawaa** [comment]
@xizhonghua 谢谢，非常好用。临时文件不是问题，反正我也是通过shell脚本调用你的工具的，我自己让shell帮忙删除就好了。
:+1:
